env:
  browser: true
  es2021: true
  node: true

extends:
  - airbnb
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended
  - plugin:prettier/recommended

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module

plugins:
  - react
  - react-hooks
  - jsx-a11y
  - prettier
  - import

rules:
  no-param-reassign: off
  no-underscore-dangle: off
  no-console: off
  import/extensions: off
  react/jsx-props-no-spreading: off
  react/react-in-jsx-scope: off
  react/prop-types: off
  react/button-has-type: error
  jsx-a11y/no-autofocus: off
  max-len: [error, { code: 100, ignoreUrls: true }]
  object-curly-newline: off
  react/jsx-one-expression-per-line: off
  react/jsx-indent-props: [error, 2]
  react/jsx-indent: [error, 2]
  indent: [error, 2]
  prettier/prettier: [error, { endOfLine: auto }]
