root: true
extends:
  - airbnb
  - plugin:jsx-a11y/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
env:
  browser: true
  es2021: true
parserOptions:
  ecmaVersion: 2021
  sourceType: module
settings:
  react:
    version: detect
rules:
  no-console: off
  no-alert: warn
  no-param-reassign: error
  no-use-before-define: error
  max-len:
    - error
    - code: 100
  react/jsx-props-no-spreading: error
  react/button-has-type: error
  jsx-a11y/no-autofocus: error
  jsx-a11y/label-has-associated-control: error
  react/react-in-jsx-scope: off
  import/no-extraneous-dependencies:
    - error
    - devDependencies: false
  react/function-component-definition: error
