root: true
env:
  browser: true
  node: true
  es2021: true

extends:
  - airbnb
  - airbnb/hooks
  - plugin:jsx-a11y/recommended
  - plugin:prettier/recommended

parserOptions:
  ecmaVersion: 2021
  sourceType: module

rules:
  # JSX
  react/jsx-filename-extension:
    - error
    - extensions:
        - .js
        - .jsx
  react/react-in-jsx-scope: off
  react/prop-types: off
  react/jsx-props-no-spreading: off
  react/function-component-definition:
    - error
    - namedComponents: arrow-function
  react/button-has-type: error
  react/self-closing-comp: error
  react/jsx-closing-bracket-location: error
  react/jsx-closing-tag-location: error
  react/jsx-first-prop-new-line: error
  react/jsx-indent: [error, 2]
  react/jsx-indent-props: [error, 2]
  react/jsx-one-expression-per-line: error
  react/jsx-max-props-per-line:
    - error
    - maximum: 1
      when: multiline

  # A11y
  jsx-a11y/no-autofocus: error
  jsx-a11y/label-has-associated-control: error

  # Common
  indent:
    - error
    - 2
  quotes:
    - error
    - single
  semi:
    - error
    - always
  comma-dangle:
    - error
    - always-multiline
  no-trailing-spaces: error
  eol-last: error
  max-len:
    - error
    - code: 100
  arrow-parens:
    - error
    - always
  curly: error

  # Redux Toolkit
  no-param-reassign: off

  # Imports
  import/no-extraneous-dependencies:
    - error
    - devDependencies: ['**/*.test.js', '**/*.spec.js', '**/setupTests.js']
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
      'newlines-between': always