env:
  browser: true
  es2021: true

extends:
  - airbnb
  - plugin:jsx-a11y/recommended
  - plugin:react/recommended

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: off
  no-param-reassign: off
  react/react-in-jsx-scope: off
  react/prop-types: off
  react/function-component-definition:
    - error
    - namedComponents: arrow-function
  import/no-extraneous-dependencies:
    - error
    - devDependencies: false
  jsx-a11y/no-autofocus: off
