env:
  browser: true
  es2021: true

extends:
  - airbnb
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended
  - plugin:prettier/recommended  # ВАЖНО: включает prettier как плагин

plugins:
  - react
  - jsx-a11y
  - prettier  # чтобы ESLint следил за стилем Prettier

parserOptions:
  ecmaVersion: 12
  sourceType: module

rules:
  arrow-parens: off
  no-param-reassign: off
  no-console: off
  no-underscore-dangle: off
  no-use-before-define: off
  import/extensions: off
  import/no-extraneous-dependencies: off
  react/react-in-jsx-scope: off
  react/jsx-props-no-spreading: off
  prettier/prettier: error  # ESLint будет считать нарушения Prettier ошибками
